### PR TITLE
Calculate prime path coverage

### PR DESCRIPTION
**Pull request by akshathsk**

### CODE REVIEW

**Comment by misto** [comment]
Thank you for the pull request. I'm still trying to figure out what to do about it though. Please elaborate on what your changes do and if this would be a benefit for all users of the repository.

**Comment by akshathsk** [comment]
> Thank you for the pull request. I'm still trying to figure out what to do about it though. Please elaborate on what your changes do and if this would be a benefit for all users of the repository.

Hi Misto,

I will be closing this PR. This is part of some ongoing research work at UIUC on microservice-based projects.

Thanks!

**Comment by misto** [comment]
No problem :-) Please let us know how it turned out!

**Comment by akshathsk** [comment]
:) Sure!

**Pull request closed without merging**
